# ===========================
# HUGGINGFACE PROFILE - H2 File
# ===========================
# We use a file-based H2 database for Hugging Face Spaces.
# This data will persist across app restarts within the container, 
# although Spaces will eventually reset it if sleeping or rebuilding.
spring.datasource.url=jdbc:h2:file:/data/gardenview;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# minimal logging for prod
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN
logging.level.root=INFO
